version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: recipe-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: recipe-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8080
    ports:
      - "8081:8080"
    volumes:
      - ./src/main/resources/keycloak:/opt/keycloak/data/import
    depends_on:
      - mongodb

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: recipe-book-service:latest
    environment:
      - JAVA_OPTS=-Dquarkus.mongodb.connection-string=mongodb://mongodb:27017 -Dquarkus.mongodb.database=recipebook -DOIDC_AUTH_SERVER_URL=http://keycloak:8080/realms/recipe-realm -DOIDC_CLIENT_SECRET=secret
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - keycloak

volumes:
  mongo_data: {}
